### ISSUE TITLE
auto command error

### ISSUE THREAD

**Issue by jrengmusic** [johnnovak/vim-walter#1]
Hi,

I'm using VIM version 8.0.1175. both in MacVim and Terminal.

Every time i opened rtconfig.rxt the following message always appear and cannot detect the filetype

> Error detected while processing BufRead Auto commands for "rtconfig.txt":
> E474: Invalid argument: filetype=walter^M

any way to resolve this?

Thanks

JRENG!

**Comment by johnnovak** [comment]
Try converting the newlines on all files from this repo to Unix style, that might fix it.

**Comment by jrengmusic** [comment]
That do the trick. Thanks John!
